### ISSUE TITLE
Survey overview endlessly shows "Loading..."

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/surveda#1433] opened 2018-10-19 02:00 UTC
Version: 5ab25d2

Steps to reproduce:
- Create a Questionnaire "q1" with a numeric step "n1" with range 1-10.
- Create a Survey "s1" using the quex "q1".
- Enable quotas for "s1", adding only a single quota for "n1" with range 1-5.
- Complete "s1" with a respondent , replying step "n1" with any number above 5.

Obtained:
When navigating to survey overview of "s1", it remains "Loading..." ad infinitum.

**Comment by lmatayoshi** [comment] 2018-10-19 02:32
Whenever quotas are enabled, a respondent completes the survey and their answer to a numeric step doesn't fall in any of the quotas, a `CompletedRespondent` entry is created with `quota_bucket_id=0`. 

This scenario is not considered in the `respondent_controller -> stats` endpoint, leading to a runtime error. Even though this error is being handled in a rescue clause, the controller handles the request with an empty JSON object, which doesn't have the necessary data to display the Survey Overview and thus it remains endlessly displaying the "Loading..." message.

Some approaches to tackle this problem can be:
- When creating a survey, ensure that all valid values for a numeric step are included in the quotas. 
- Consider the previously described scenario in the `respondent_controller -> stats` endpoint, in order to avoid the runtime error.
- Adapt `SurveyShow.jsx`, so that the survey overview could be displayed despite not having the necessary data.

**Comment by matiasgarciaisaia** [comment] 2024-04-08 23:08
This is in fact a duplicate of #1471 - which was reported later, but we took it as the canonical ticket for this error.

**Closed by matiasgarciaisaia** 2024-04-08 23:08 UTC
