### ISSUE TITLE
Channel capacity is being lost under certain circumstances

### ISSUE THREAD

**Issue by aeatencio** [instedd/surveda#2155] opened 2022-09-16 21:04 UTC
Hypothesis: when an existent channel is synced the settings are recreated without considering the channel capacity. Then the capacity is reset and defaulted. In both [Verboice](https://github.com/instedd/surveda/blob/880576dda040805b6d79c5622d2fd94324f8637f/lib/ask/runtime/verboice_channel.ex#L218-L221) and [Nuntium](https://github.com/instedd/surveda/blob/880576dda040805b6d79c5622d2fd94324f8637f/lib/ask/runtime/nuntium_channel.ex#L253-L256).

[This log](https://github.com/instedd/surveda/files/9587215/error_capacity.log) is taken from the test that allowed @manumoreira and I find this bug testing how the retries work on IVR mode.

Line 2462:

- The ChannelBroker was initialized with no capacity in its settings: `settings: %{"verboice_channel" => "Callcentric 102", "verboice_channel_id" => 437}` after a crash.

We supposed we messed things up by syncing channels during the test, with enough luck to find this bug and have the proper logs.

In the same log (line 2443) there's also the stack trace of the crash previous to the channel capacity loss.

**Comment by diegoliberman** [comment] 2023-04-03 14:23
We couldn't reproduce this issue, hence for the time being it's on hold.  If the issue doesn't happen again for a couple of months, we should just close it.

**Closed** 2023-04-19 19:01 UTC
Labels: bug, on hold
