### ISSUE TITLE
Missing `n` of respondents needed in Cockpit

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1939] opened 2021-08-31 14:41 UTC
In https://surveda-ph.org/projects/26/surveys/381 the number of respondents needed to complete the target is missing
<img width="1277" alt="Screen Shot 2021-08-31 at 11 39 35" src="https://user-images.githubusercontent.com/31930782/131523243-ff7c466d-269e-42aa-a73a-23ed98b1d198.png">

**Comment by diegoliberman** [comment] 2021-09-28 16:31
Duplicate of #1947

**Closed by diegoliberman** 2021-09-28 16:31 UTC
