### ISSUE TITLE
Pages count fail in panel surveys

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1941] opened 2021-09-22 15:51 UTC
In panel surveys with less than 9 waves, all the waves should be shown on page 1.
Something is not worlimng properly in the page counter (at the bottom right corner)
<img width="1616" alt="Screen Shot 2021-09-22 at 12 47 09" src="https://user-images.githubusercontent.com/31930782/134377607-c790b473-a08c-4248-8f29-89b1475461ea.png">

**Comment by diegoliberman** [comment] 2021-09-28 16:33
Duplicate of #1949

**Closed** 2021-09-28 16:37 UTC
Labels: bug
