### ISSUE TITLE
Change new panel survey wave icon

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1940] opened 2021-09-22 15:45 UTC
Currently, we are using [reply icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Areplay%3A) we should replace that one with [repeat one icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Arepeat_one%3A)

**Comment by diegoliberman** [comment] 2021-09-28 16:32
Duplicate of #1948

**Closed by diegoliberman** 2021-09-28 16:32 UTC
