### ISSUE TITLE
Verboice channels should not require a default call flow

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#775] opened 2017-03-23 12:37 UTC
Since a call in Verboice can be executed using a Channel without default call flow for incoming calls users can expect the same behavior using Ask.

If default call flow for incoming calls must be required we should display an explanation in the Channels index.

<img width="1540" alt="screen shot 2017-03-23 at 9 35 14 am" src="https://cloud.githubusercontent.com/assets/518152/24247828/0d680158-0fac-11e7-9006-340c884bd902.png">

**Comment by edjez** [comment] 2017-03-24 04:06
(note they are not required in Verboice today,nor for a verboice channel used in Ask, as of last week - but are a nice addition to set up what happens when someone calls in)

**Comment by mmuller** [comment] 2017-03-27 13:20
@edjez now (version 0.7.2) if the Verboice Channel has no a Call Flow assigned for incoming calls, Ask cannot send a Survey using that Channel. 
The call is marked as `Active` in Ask but it is not queued in Verboice.

<img width="277" alt="screen shot 2017-03-27 at 10 16 58 am" src="https://cloud.githubusercontent.com/assets/518152/24358165/936b859a-12d6-11e7-8ed7-be7b96481c9b.png">

**Comment by nditada** [comment] 2017-03-28 21:25
The issue is that a Verboice channel used in Ask requires a default callflow to be setup. This is due to Verboice requiring a project for each call, i.e. Verboice cannot handle calls that don't belong to a project. This requires a heavy refactor in Verboice and the workaround is simple. Let's postpone it until we review how to setup channels directly from Ask.

**Comment by mmuller** [comment] 2019-11-19 19:30
This issue is still present in version d6b2b6b.
Channels created from Ask doesn't have default callflow in Verboice.

**Comment by manumoreira** [comment] 2019-12-26 19:08
it is fixed now ([48fdf0a](https://github.com/instedd/surveda/commit/48fdf0aeacd4268ad05ad5d87351d4065117e62c))
When using a channel that has no flow surveda creates a default flow in verboice.

**Closed by manumoreira** 2019-12-26 19:08 UTC
Labels: enhancement, on hold
