### ISSUE TITLE
Time at selected timezone is failing after midnight

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1736] opened 2020-06-05 19:33 UTC
<img width="564" alt="laHora25" src="https://user-images.githubusercontent.com/31930782/83915713-2d70b100-a74a-11ea-97f1-732f81d73d43.png">

**Comment by ismaelbej** [comment] 2024-09-10 19:38
It seems this issue was cause a change in Chrome. It was reported here https://stackoverflow.com/questions/60886186/intl-datetimeformat-shows-time-being-2459. Here is a more detailed description of the issue https://github.com/moment/luxon/issues/726#issuecomment-675151145.

The issue is fixed in the current Chrome version 128.0.6613.120. Tested it is still working fine in Firefox 130.0,

**Comment by matiasgarciaisaia** [comment] 2024-09-13 19:06
I've just tested running a local version of the 0.28.0 Docker image (`Version: 0.28.0 (build 4727)`), and both Firefox 130.0 and Chrome 128.0.6613.120 properly show `Time at selected timezone: Saturday 00:02`.
![Screenshot 2024-09-13 at 4 03 11 PM](https://github.com/user-attachments/assets/3408f552-8c37-4489-871b-e40c576c831a)

Great research, @ismaelbej!

Let's close the issue 👍

**Closed by matiasgarciaisaia** 2024-09-13 19:06 UTC
Labels: good-first-issue
